#!/bin/sh

_scratch=0
_home=0

primary_box='malcha'
_box=${_box:-${primary_box}}

_timestamp=$(date +%F-%H%M%S)

fetch_data() {
	_basedir='/home/alexanderm'
	[ -n "$2" ] \
		&& _source="alexanderm@malcha.physik.fu-berlin.de:$2" \
		|| _source="alexanderm@malcha.physik.fu-berlin.de:${_basedir}/crosstalk/test"
	[ -n "$3" ] \
		&& _destination="$3" \
		|| _destination="$HOME"/inbox/Hangar_SSH/"${_timestamp}"

	rsync -avzhP -e ssh "${_source}" "${_destination}"
}

send_data() {
	[ -n "$2" ] \
		&& _source="$2" \
		|| _source="$HOME"/crosstalk/test
	[ -n "$3" ] \
		&& _destination="$3" \
		|| _destination="$HOME"/Cloud/fubox/masterarbeit/DataStaging/"${_timestamp}"
	cp -Rv "${_source}" "${_destination}"
}

while getopts b:sh arg; do
    case ${arg} in
        b) _box="${OPTARG}" ;;
        s) _scratch=1 ;;
        h) _home=1 ;;
        *) usage
    esac
done
shift $((OPTIND -1))

case $1 in
	f*) fetch_data "$@" ;;
	s*) send_data "$@" ;;
esac
